first compose netwoking try
MindAsEngine/twg-backend pull request #42
Opened 2024-03-23 19:16 UTC by ProdamGaraj

2024-03-23 19:18 UTC, olshanskyvv commented on backend_compose.yaml
Почему порт 1337?

2024-03-23 19:22 UTC, olshanskyvv commented on database-compose.yaml
> +  redis-commander:
Как будто нам это не надо

2024-03-23 19:24 UTC, olshanskyvv requested changes
Исправить порты у бэка и redis-commander

2024-03-23 19:34 UTC, olshanskyvv approved these changes
OK

2024-03-24 00:53 UTC, ProdamGaraj commented
FIxed compose

2024-03-24 00:54 UTC, merged